#spring:
#  datasource:
#    url: jdbc:h2:mem:university;NON_KEYWORDS=USER
#    driverClassName: org.h2.Driver
#    username: root
#    password: password
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate.ddl-auto: update
#    defer-datasource-initialization: true
#  data.jpa.repositories.bootstrap-mode: default
#  h2.console.enabled: true

spring:
  datasource:
    url: jdbc:h2:mem:university
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect